"""Add release_date to Movie model

Revision ID: 252ae4250ea0
Revises: 60fb0525e323
Create Date: 2024-11-24 20:58:58.354434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252ae4250ea0'
down_revision = '60fb0525e323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
