"""Add release_date to Movie model

Revision ID: 44cb9a0d17fb
Revises: 252ae4250ea0
Create Date: 2024-11-24 23:31:27.930625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cb9a0d17fb'
down_revision = '252ae4250ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_ticket_movie', 'movie', ['movie_id'], ['id'])  # Add a name for the foreign key
        batch_op.drop_column('barcode')
        batch_op.drop_column('num_seats')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_seats', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_ticket_movie', type_='foreignkey')  # Use the same name as in the upgrade
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
