"""Add showtime to Movie model

Revision ID: 60fb0525e323
Revises: 0160c4bf0342
Create Date: 2024-11-24 20:12:49.738208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60fb0525e323'
down_revision = '0160c4bf0342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
